import { mkdirSync, writeFileSync, readFileSync, existsSync } from 'node:fs';
import { releaseLocales } from '../src/shared/i18n/release-copy';
import { LOCALES } from '../src/shared/i18n/core';
import config from '../config/release.json';
const descriptions: Record<string, string> = {
  en: 'ChatGPT Read Aloud controls: pause, seek, speed, volume, audio downloads, shortcuts and response buttons.',
  'zh-CN': 'ChatGPT 朗读控件：暂停、跳转、调速、音量、音频下载、快捷键和回复按钮。',
  'zh-TW': 'ChatGPT 朗讀控制項：暫停、跳轉、調速、音量、音訊下載、快速鍵和回覆按鈕。',
  vi: 'Điều khiển Đọc to của ChatGPT: tạm dừng, tua, tốc độ, âm lượng, tải âm thanh, phím tắt và nút đọc phản hồi.',
  th: 'ควบคุมการอ่านออกเสียง ChatGPT: หยุดชั่วคราว เลื่อน ความเร็ว ระดับเสียง ดาวน์โหลด ปุ่มลัด และปุ่มอ่านคำตอบ',
  es: 'Controles de Leer en voz alta de ChatGPT: pausa, avance, velocidad, volumen, descargas de audio y atajos.',
  'pt-BR': 'Controles de Ler em voz alta do ChatGPT: pausa, avanço, velocidade, volume, downloads de áudio e atalhos.',
  'pt-PT': 'Controlos de Ler em voz alta do ChatGPT: pausa, avanço, velocidade, volume, transferências de áudio e atalhos.',
  ru: 'Управление чтением вслух ChatGPT: пауза, перемотка, скорость, громкость, скачивание аудио и сочетания клавиш.',
  hi: 'ChatGPT Read Aloud के कंट्रोल: रोकें, आगे-पीछे जाएँ, गति और आवाज़ बदलें, ऑडियो डाउनलोड करें और शॉर्टकट इस्तेमाल करें।',
  fr: 'Contrôlez la lecture à voix haute de ChatGPT : pause, avance, vitesse, volume, téléchargement audio et raccourcis.',
  de: 'ChatGPT Vorlesen steuern: Pause, Spulen, Tempo, Lautstärke, Audio-Downloads, Tastenkürzel und Antwortschaltflächen.',
  ja: 'ChatGPTの読み上げを操作：一時停止、シーク、速度、音量、音声ダウンロード、ショートカット、回答の読み上げボタン。',
  ko: 'ChatGPT 소리 내어 읽기 제어: 일시 정지, 탐색, 속도, 음량, 오디오 다운로드, 단축키, 응답 읽기 버튼.',
  id: 'Kontrol Baca dengan lantang ChatGPT: jeda, geser, kecepatan, volume, unduh audio, pintasan, dan tombol respons.',
  it: 'Controlli di lettura ad alta voce ChatGPT: pausa, avanzamento, velocità, volume, download audio e scorciatoie.',
  tr: 'ChatGPT Sesli Oku kontrolleri: duraklatma, sarma, hız, ses düzeyi, ses indirme, kısayollar ve yanıt düğmeleri.',
};
let listings = '# Localized Chrome and Edge listing copy\n\nGenerated by `bun run scripts/build-store-copy.ts`. Console updates must be verified separately; packaged translations do not update store descriptions. Apply v1.2.0 feature copy when that version is available in the corresponding store.\n\n';
for (const [code, c] of Object.entries(releaseLocales)) {
  const folder = `public/_locales/${code.replace('-', '_')}`;
  const file = `${folder}/messages.json`;
  const old = existsSync(file) ? JSON.parse(readFileSync(file, 'utf8')) : {};
  const description = descriptions[code];
  if (!description || description.length > 132) throw new Error(`Invalid store summary: ${code}`);
  const title = old.extensionName?.message || 'ChatGPT Audio Controls — ' + LOCALES[code as keyof typeof LOCALES].content.tooltips.readAloud;
  mkdirSync(folder, { recursive: true });
  writeFileSync(file, JSON.stringify({ extensionName: { message: title }, extensionDescription: { message: description }, extensionActionTitle: { message: 'ChatGPT Audio Controls' }, visibilityCommand: { message: c.visibilityShortcut } }, null, 2) + '\n');
  const site = config.siteUrl + (code === 'en' ? '' : code + '/');
  listings += `## ${code}\n\n### Title\n\n${title}\n\n### Summary\n\n${description}\n\n### Description\n\n${c.siteIntro}\n\n${c.quickStartBody}\n\n${c.compactHelp}\n\n${c.hideHint}\n${c.idleOnly} / ${c.allUi}\n\n${c.visibilityShortcut}: Alt+Shift+Y (Windows/Linux) / Option ⌥+Shift ⇧+Y (macOS). ${c.customize}.\n${c.shortcutScope}\n\n${c.sourceFormat}\n\n${c.desktop}\n\n${c.privacyBody}\n\n${c.feedbackPolicy}\n\n${c.independent}\n\n${c.help}: ${site}#help\n${c.privacy}: ${site}#privacy\n\n`;
}
writeFileSync('docs/STORE-LISTINGS.md', listings.trimEnd() + '\n');
console.log('Generated 17 manifest catalogs and store listings.');
